# Generated by Django 4.2.30 on 2026-09-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_participant_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='seeded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
    ]
